name: Deploy to Hosting via FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: WebsiteFTP

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy files via FTP
      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.WebsiteFTP.FTP_HOST }}
          username: ${{ secrets.WebsiteFTP.FTP_USERNAME }}
          password: ${{ secrets.WebsiteFTP.FTP_PASSWORD }}
          local-dir: dist
          port: '21'
